version: "3.7"

services:
  db:
    image: postgres:13.1
    container_name: store_db
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env.db
    expose:
      - 5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000
    restart: always
