# Generated by Django 3.2.10 on 2022-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
